# Generated by Django 4.1.7 on 2023-02-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_remove_elevator_current_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=1)),
                ('current_status', models.CharField(choices=[('IDLE', 'Idle'), ('MOVING', 'Moving'), ('DOOR_OPEN', 'Door Open'), ('REACHED_TOP', 'Reached Top'), ('REACHED_BOTTOM', 'Reached Bottom')], default='IDLE', max_length=20)),
                ('button_pressed', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('FLOOR', 'Floor'), ('FLOOR_1', 'Floor 1'), ('FLOOR_2', 'Floor 2'), ('FLOOR_3', 'Floor 3')], default='BOTTOM', max_length=20)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.elevator')),
                ('requests', models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='ElevatorStatus',
        ),
    ]
