# Generated by Django 4.1.7 on 2023-02-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_building_floors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='ctreated_by',
            new_name='created_by',
        ),
    ]
