# Generated by Django 4.1.7 on 2023-02-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_delete_elevatormanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='current_floor',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='is_door_open',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='is_moving',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='is_reached_bottom',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='is_reached_top',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='requests',
        ),
        migrations.AddField(
            model_name='elevator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator',
            name='ctreated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElevatorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=1)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_door_open', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reached_top', models.BooleanField(default=False)),
                ('is_reached_bottom', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.building')),
                ('requests', models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
