# Generated by Django 4.1.7 on 2023-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_elevatoroperations_alter_building_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='elevatoroperations',
            name='button_pressed',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('FLOOR', 'Floor')], default='BOTTOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='elevatoroperations',
            name='current_status',
            field=models.CharField(choices=[('REACHED', 'Reached'), ('MOVING', 'Moving'), ('IDLE', 'Idle')], default='IDLE', max_length=20),
        ),
    ]
